# Generated by Django 3.2.16 on 2023-01-25 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
